# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tsgeneral',
                'doc_host': 'https://hypercubeanalytics.github.io',
                'git_url': 'https://github.com/hypercubeanalytics/tsgeneral',
                'lib_path': 'tsgeneral'},
  'syms': { 'tsgeneral.hcingest': { 'tsgeneral.hcingest.print_something': ('ingest.html#print_something', 'tsgeneral/hcingest.py'),
                                    'tsgeneral.hcingest.read': ('ingest.html#read', 'tsgeneral/hcingest.py'),
                                    'tsgeneral.hcingest.simple_validator': ('ingest.html#simple_validator', 'tsgeneral/hcingest.py')}}}
